### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haltcase** [joncasey/my-babel-standalone#1]
Obviously the Babel code is MIT but your update & build code isn't covered by that &mdash; I'm looking at making my own version of `@babel/standalone` to fit my needs and would like to use this as the base if possible (it's very clean 👍). Is this MIT also?

**Comment by joncasey** [comment]
Thanks, @citycide. I've added MIT license file to match what was in package.json.
Best of luck to you! And happy to help, if you run into any issues.
